INREL-3967: Merge infinite amp theme 8.x-2.x-dev into 8.x-2.x
BurdaMagazinOrg/theme-infinite_amp pull request #15
Opened 2018-05-16 14:53 UTC by alex-schell

## [INREL-3967](https://jira.burda.com/browse/INREL-3967) 
Merge 8.x-2.x-dev into 8.x-2.x

## How to test:
Please check to see if anyone can foresee any issues with this merge

2018-05-17 07:30 UTC, mgoedecke commented
lgtm

2018-05-17 07:30 UTC, mgoedecke approved these changes
lgtm

2018-05-17 08:04 UTC, saviomuc requested changes

2018-05-17 08:04 UTC, saviomuc commented on templates/system/page--front.html.twig
> +{#
Needs to be moved to Instyle

2018-05-17 08:04 UTC, saviomuc commented on templates/paragraphs/paragraph--social.html.twig
> +    {{ content.field_embed_description }}
Needs to be moved to instyle

2018-05-17 08:04 UTC, saviomuc commented on templates/field/field--paragraph--field-embed-description.html.twig
> +  {%- for item in items -%}
Needs to be moved to Instyle

2018-05-22 10:26 UTC, alex-schell commented
@saviomuc Everything done. See also here: https://github.com/BurdaMagazinOrg/instyle-web/pull/360/commits

2018-05-24 09:48 UTC, saviomuc approved these changes
LGTM :shipit:

2018-05-24 11:28 UTC, merged